"""
- The state is a shared data structure that holds the current information or context
  of an application.

- In simple terms, it is like the application's memory, keeping track of the variables
  and data that nodes can access and modify as they execute.

Analogy:
Whiteboard in a meeting room: 
The node is a person, writing and reading from the whiteboard. The whiteboard represents the state, where everyone 
can see and update the information.
"""

"""
- Node are individual function or operations that perform specific tasks within the graph.

- Each node receives input (often the current state), process it, and produces an output or an updated state.

Analogy:
Assembly line in a factory:
Each worker (node) performs a specific task on the product (state). The product moves along the assembly line, 
and each worker contributes to its transformation, such as, attach a part, paint it, inspect quality and so on.
"""

"""
- Graph in LangGraph is the overaching structure that maps out how different tasks(nodes) are connected and executed

- It visually represents the workflow, showing the sequence and conditional paths between various operations.
"""

"""
- Edge are the connections between nodes that determine the flow of execution

- They tell us which node should be executed next after the current has completed its work.
"""

"""
- Conditional edges are specialized connections that decide the next node to execute based on specific condition or logic applied to the current state.

Analogy:
Traffic Light:
Green means go, red means stop, yellow means slow down. The condition(light color) decides next step.
"""

"""
- START node is a virtual entry point in Langgraph, marking where the workflow begins.

- It doesn't perform any operation itself but serves as the designated starting position for the graph's execution.
"""

"""
- END node signifies the end of a workflow in langgraph

- Upon reaching this node, the execution of the graph stops, indicating that all intended processes have been completed.
"""

"""
- Tools are specialized functions or utilities that nodes can utilize to perform specific tasks such as fetching data
  from API.

- They enhance capabilities of nodes by providing additional functionalities.

- Nodes are part of graph's structure while tools are the functionalities used within the node.
"""

"""
- ToolNode is just a special node whose main job is to run a tool.

- It connects the tool's output back into the state, so other nodes can use that information.
"""

"""
- A StateGraph is a class in langgraph used to build and compile the graph structure.

- It manages nodes, edges and overall state, ensuring that the workflow operates in a unified way and the data flows correctly 
  between components.

Analogy:
Blueprint of a building: Just as a blueprint outlines the design and connections within a building, a StateGraph defines the
structure and flow of the workflow.
"""

"""
- Runnable in langgraph is a standardized executable component that performs a specific task with an AI workflow.

- It serves as a fundamental building block, allowing for us to create modular systems.
"""

"""
Messages
- Human message: Represents inputs from a human
- System message: Used to provide instructions or context to model
- Function message: Represents the result of a function call.
- AI message: Represents responses generated by AI models
- Tool message: Similar to function message, but specific to tool usage
"""